jobs/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from django.contrib import admin
from django.urls import path, include

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Jobs Portal API",
        default_version="v1",
        description="Jobs Portal Api Description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny, ),
)

lang_patterns = i18n_patterns(
    path("", include("jobsapp.urls")),
    path("", include("accounts.urls")),
)

urlpatterns = lang_patterns + [
    url(r"^i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path(
        "api/",
        include([
            path("swagger", schema_view.with_ui("swagger", cache_timeout=0)),
            path("", include("accounts.api.urls")),
            path("", include("jobsapp.api.urls")),
        ]),
    ),
    path("social-auth/", include("social_django.urls", namespace="social")),
    # url(r"^(?P<url>.*/)$", flatpages_views.flatpage),
]

jobsapp/urls.py
from django.urls import path, include

from .views import HomeView, SearchView, DashboardView, ApplicantsListView, ApplicantPerJobView
from .views import JobCreateView, JobUpdateView, EmployeeMyJobsListView, FavoriteListView
from .views import ApplyJobView, JobListView, JobDetailsView, favorite, filled

app_name = "jobs"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("favorite/", favorite, name="favorite"),
    path("search/", SearchView.as_view(), name="search"),
    path(
        "employer/dashboard/",
        include([
            path("", DashboardView.as_view(), name="employer-dashboard"),
            path(
                "all-applicants/",
                ApplicantsListView.as_view(),
                name="employer-all-applicants",
            ),
            path(
                "applicants/<int:job_id>/",
                ApplicantPerJobView.as_view(),
                name="employer-dashboard-applicants",
            ),
            path("mark-filled/<int:job_id>/", filled, name="job-mark-filled"),
            path("jobs/create/",
                 JobCreateView.as_view(),
                 name="employer-jobs-create"),
            path("jobs/<int:id>/edit/",
                 JobUpdateView.as_view(),
                 name="employer-jobs-edit"),
        ]),
    ),
    path(
        "employee/",
        include([
            path(
                "my-applications",
                EmployeeMyJobsListView.as_view(),
                name="employee-my-applications",
            ),
            path("favorites",
                 FavoriteListView.as_view(),
                 name="employee-favorites"),
        ]),
    ),
    path("apply-job/<int:job_id>/", ApplyJobView.as_view(), name="apply-job"),
    path("jobs/", JobListView.as_view(), name="jobs"),
    path("jobs/<int:id>/", JobDetailsView.as_view(), name="jobs-detail"),
]

jobsapp/api/views/employer.py
from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated

from jobsapp.api.permissions import IsEmployer
from jobsapp.api.serializers import ApplicantSerializer
from jobsapp.models import Applicant


class ApplicantsListAPIView(ListAPIView):
    serializer_class = ApplicantSerializer
    permission_classes = [IsAuthenticated, IsEmployer]

    def get_queryset(self):
        user = self.request.user
        return Applicant.objects.filter(job__user_id=user.id)

jobsapp/views/employer.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView

from jobsapp.decorators import user_is_employer
from jobsapp.forms import CreateJobForm
from jobsapp.models import Job, Applicant
from tags.models import Tag

ROUTE_JOBS_EMPLOYER_DASHBOARD = "jobs:employer-dashboard"
ROUTE_ACCOUNTS_LOGIN = "accounts:login"

class DashboardView(ListView):
    model = Job
    template_name = "jobs/employer/dashboard.html"
    context_object_name = "jobs"

    @method_decorator(login_required(login_url=reverse_lazy(ROUTE_ACCOUNTS_LOGIN)))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user_id=self.request.user.id)


class ApplicantPerJobView(ListView):
    model = Applicant
    template_name = "jobs/employer/applicants.html"
    context_object_name = "applicants"
    paginate_by = 1

    @method_decorator(login_required(login_url=reverse_lazy(ROUTE_ACCOUNTS_LOGIN)))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return Applicant.objects.filter(
            job_id=self.kwargs["job_id"]).order_by("id")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["job"] = Job.objects.get(id=self.kwargs["job_id"])
        return context


class JobCreateView(CreateView):
    template_name = "jobs/create.html"
    form_class = CreateJobForm
    extra_context = {"title": "Post New Job"}
    success_url = reverse_lazy(ROUTE_JOBS_EMPLOYER_DASHBOARD)

    def __init__(self, *args, **kwargs):
        super().__init__(self, *args, **kwargs)
        self.object = None

    @method_decorator(login_required(login_url=reverse_lazy(ROUTE_ACCOUNTS_LOGIN)))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy(ROUTE_ACCOUNTS_LOGIN)
        if self.request.user.is_authenticated and self.request.user.role != "employer":
            return reverse_lazy(ROUTE_ACCOUNTS_LOGIN)
        return super().dispatch(self.request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tags"] = Tag.objects.all()
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)


@method_decorator(login_required(login_url=reverse_lazy(ROUTE_ACCOUNTS_LOGIN)),
                  name="dispatch")
@method_decorator(user_is_employer, name="dispatch")
class JobUpdateView(UpdateView):
    template_name = "jobs/update.html"
    form_class = CreateJobForm
    extra_context = {"title": "Edit Job"}
    slug_field = "id"
    slug_url_kwarg = "id"
    success_url = reverse_lazy(ROUTE_JOBS_EMPLOYER_DASHBOARD)
    context_object_name = "job"

    def __init__(self, *args, **kwargs):
        super().__init__(self, *args, **kwargs)
        self.object = None

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return Job.objects.filter(user_id=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tags"] = Tag.objects.all()
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "Job updated successfully")
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)


class ApplicantsListView(ListView):
    model = Applicant
    template_name = "jobs/employer/all-applicants.html"
    context_object_name = "applicants"

    def get_queryset(self):
        return self.model.objects.filter(job__user_id=self.request.user.id)


@login_required(login_url=reverse_lazy(ROUTE_ACCOUNTS_LOGIN))
def filled(request, job_id=None):
    try:
        job = Job.objects.get(user_id=request.user.id, id=job_id)
        job.filled = True
        job.save()
    except IntegrityError as e:
        print(e.message)
        return HttpResponseRedirect(reverse_lazy(ROUTE_JOBS_EMPLOYER_DASHBOARD))
    return HttpResponseRedirect(reverse_lazy(ROUTE_JOBS_EMPLOYER_DASHBOARD))

templates/jobs/employer/all-applicants.html
{% extends 'base.html' %}
{% block title %}
    Applicants
{% endblock %}
{% load static %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">All applicants who applied for your positions</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                {% for applicant in applicants %}
                    <div class="col-lg-6">
                        <div class="box applicant">
                            <h4>{{ applicant.user.get_full_name }}</h4>
                            <p><strong>Applied position: {{ applicant.job.title }}</strong></p>
                            <a href="#" data-toggle="modal" data-target="#contact-modal"
                               class="btn btn-outline-white-secondary btn-sm">
                                <em class="fa fa-envelope"></em>Contact
                            </a>
                            <p>
                                <span class="badge badge-info">Applied {{ applicant.created_at.astimezone }}</span>
                            </p>
                            <div class="d-flex justify-content-between">
                                <p class="intro"></p>
                                <div class="image">
                                    <img src="{% static 'img/avatar.png' %}" alt=""
                                         class="img-fluid rounded-circle">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-md-12">
                            <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.previous_page_number }}"
                                               class="page-link">&laquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&laquo;</a>
                                        </li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item active">
                                                <a class="page-link">{{ i }}</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.next_page_number }}"
                                               class="page-link">&raquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                {% else %}
                    <h3>No Applicants</h3>
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/employer/applicants.html
{% extends 'base.html' %}
{% block title %}
    Applicants
{% endblock %}
{% load static %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Applicants for the <span class="accent">{{ job.title }}</span> position</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                {% for applicant in applicants %}
                    <div class="col-lg-6">
                        <div class="box applicant">
                            <h4>{{ applicant.user.get_full_name }}</h4>
                            <a href="#" data-toggle="modal" data-target="#contact-modal"
                               class="btn btn-outline-white-secondary btn-sm">
                                <em class="fa fa-envelope"></em>Contact
                            </a>
                            <p>
                                <span class="badge badge-info">Applied {{ applicant.created_at.astimezone }}</span>
                            </p>
                            <div class="d-flex justify-content-between">
                                <p class="intro"></p>
                                <div class="image">
                                    <img src="{% static 'img/avatar.png' %}" alt=""
                                         class="img-fluid rounded-circle">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-md-12">
                            <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.previous_page_number }}"
                                               class="page-link">&laquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&laquo;</a>
                                        </li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item active">
                                                <a class="page-link">{{ i }}</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.next_page_number }}"
                                               class="page-link">&raquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                {% else %}
                    <h3>No Applicants Applied For This Job</h3>
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/employer/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Dashboard
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Dashboard</h1>
                    <p class="lead text-center">All created jobs</p>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-right mb-5">
                    <a href="{% url 'jobs:employer-jobs-create' %}" class="btn btn-outline-white-primary">
                        <em class="fa fa-plus"></em>Add new position
                    </a>
                </div>
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-client-dashboard">
                            <caption>Opening Jobs</caption>
                            <thead>
                            <tr>
                                <th scope="col">Job title</th>
                                <th scope="col">Position filled</th>
                                <th scope="col">Date posted</th>
                                <th scope="col">Date expiring</th>
                                <th scope="col">Applicants</th>
                                <th scope="col">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for job in jobs %}

                                <tr>
                                    <th scope="row"><a href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a>
                                    </th>
                                    <td>
                                        {% if job.filled %}
                                            <span class="badge badge-success">Filled</span>
                                        {% else %}
                                            <span class="badge badge-secondary">Not Filled</span>
                                        {% endif %}
                                    </td>
                                    <td>{{ job.created_at }}</td>
                                    <td>{{ job.last_date }}</td>
                                    <td>
                                        <a href="{% url 'jobs:employer-dashboard-applicants' job.id %}"
                                           class="btn btn-success">
                                            <em class="fa fa-users"></em>{{ job.applicants.count }}
                                            <span class="hidden-xs hidden-sm">Applicants</span>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'jobs:employer-jobs-edit' job.id %}" class="btn btn-outline-white-secondary">
                                            <em class="fa fa-edit"></em>Edit
                                        </a>
                                        <br>
                                        {% if job.filled %}
                                            <a href="{% url 'jobs:job-mark-filled' job.id %}"
                                               class="btn btn-outline-white-secondary">
                                                <em class="fa fa-check-circle-o"></em>
                                                <span class="hidden-xs hidden-sm">Filled</span>
                                            </a><br>
                                        {% else %}
                                            <a href="{% url 'jobs:job-mark-filled' job.id %}"
                                               class="btn btn-outline-white-secondary">
                                                <em class="fa fa-check-circle-o"></em>
                                                <span class="hidden-xs hidden-sm">Mark as </span>filled
                                            </a><br>
                                        {% endif %}
                                        <a href="#" class="btn btn-outline-white-secondary">
                                            <em class="fa fa-times-circle-o"></em>Delete
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="pages">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                <li class="page-item"><a href="#" aria-label="Previous" class="page-link"><span
                                        aria-hidden="true">«</span><span class="sr-only">Previous</span></a></li>
                                <li class="page-item active"><a href="#" class="page-link">1</a></li>
                                <li class="page-item"><a href="#" class="page-link">2</a></li>
                                <li class="page-item"><a href="#" class="page-link">3</a></li>
                                <li class="page-item"><a href="#" class="page-link">4</a></li>
                                <li class="page-item"><a href="#" aria-label="Next" class="page-link"><span
                                        aria-hidden="true">»</span><span class="sr-only">Next</span></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}